<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="K463LTRV" failures="1" tests="1" name="runner.NetworkTestRunner" time="29.267" errors="0" timestamp="2024-05-27T17:31:59 IST" skipped="0">
  <testcase classname="runner.NetworkTestRunner" name="runScenario" time="29.267">
    <failure message="expected [T-Mobile (Temporarily unavailable)] but found [T-Mobile]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [T-Mobile (Temporarily unavailable)] but found [T-Mobile]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepdefenition.StepDefs.in_calls_sms_section_to_be_added(StepDefs.java:42)
at âœ½.In calls & sms section "T-Mobile (Temporarily unavailable)" to be added(file:///C:/Users/268859/Desktop/mobileaplications/SettingsApp/src/test/resources/features/network.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.NetworkTestRunner -->
